/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/z4bzumkYaMB
 */
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table as TableUI,
} from "@/components/ui/table";

export function Table() {
  return (
    <div className="overflow-x-auto">
      <TableUI>
        <TableHeader>
          <TableRow>
            <TableHead className="w-[120px]" />
            <TableHead>Match 1</TableHead>
            <TableHead>Match 2</TableHead>
            <TableHead>Match 3</TableHead>
            <TableHead>Match 4</TableHead>
            <TableHead>Match 5</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow>
            <TableCell className="font-medium">Alice</TableCell>
            <TableCell className="bg-green-100">0-2</TableCell>
            <TableCell>2-0</TableCell>
            <TableCell className="bg-red-100">0-2</TableCell>
            <TableCell>2-0</TableCell>
            <TableCell className="bg-red-100">0-2</TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="font-medium">Bob</TableCell>
            <TableCell>2-0</TableCell>
            <TableCell className="bg-red-100">0-2</TableCell>
            <TableCell className="bg-red-100">0-2</TableCell>
            <TableCell>2-0</TableCell>
            <TableCell className="bg-red-100">0-2</TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="font-medium">Charlie</TableCell>
            <TableCell className="bg-red-100">0-2</TableCell>
            <TableCell>2-0</TableCell>
            <TableCell>2-0</TableCell>
            <TableCell className="bg-red-100">0-2</TableCell>
            <TableCell>2-0</TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="font-medium">Diana</TableCell>
            <TableCell>2-0</TableCell>
            <TableCell>2-0</TableCell>
            <TableCell className="bg-red-100">0-2</TableCell>
            <TableCell>2-0</TableCell>
            <TableCell>2-0</TableCell>
          </TableRow>
        </TableBody>
      </TableUI>
    </div>
  );
}
