/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4GBxx9CDHco
 */
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table,
} from "@/components/ui/table";
import { Input } from "@/components/ui/input";

export function Wyniki() {
  return (
    <div className="bg-gray-800 p-4 ">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead className="bg-gray-900 text-white w-150">User</TableHead>
            <TableHead className="bg-gray-900 text-white w-150">
              <div className="flex items-center justify-center">
                <img
                  alt="Poland flag"
                  className="mr-2"
                  height="16"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "24/16",
                    objectFit: "cover",
                  }}
                  width="24"
                />
                <span>Polska - Francja</span>
                <img
                  alt="France flag"
                  className="ml-2"
                  height="16"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "24/16",
                    objectFit: "cover",
                  }}
                  width="24"
                />
              </div>
              <div className="flex items-center justify-center">
                <img
                  alt="Poland flag"
                  className="mr-2"
                  height="16"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "24/16",
                    objectFit: "cover",
                  }}
                  width="24"
                />
                <span>Polska - Francja</span>
                <img
                  alt="France flag"
                  className="ml-2"
                  height="16"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "24/16",
                    objectFit: "cover",
                  }}
                  width="24"
                />
              </div>
            </TableHead>
            <TableHead className="bg-gray-900 text-white w-150">
              <div className="flex items-center justify-center">
                <img
                  alt="Netherlands flag"
                  className="mr-2"
                  height="16"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "24/16",
                    objectFit: "cover",
                  }}
                  width="24"
                />
                <span>Holandia - Australia</span>
                <img
                  alt="Australia flag"
                  className="ml-2"
                  height="16"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "24/16",
                    objectFit: "cover",
                  }}
                  width="24"
                />
              </div>
              <div>16.00 16.04.2024</div>
            </TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow>
            <TableCell className="bg-gray-700 text-white">Ada</TableCell>
            <TableCell className="bg-red-500">
              <div className="flex justify-around">
                <Input
                  className="bg-red-500 text-white w-8 text-center"
                  placeholder="4"
                  type="text"
                />
                <span>-</span>
                <Input
                  className="bg-red-500 text-white w-8 text-center"
                  placeholder="5"
                  type="text"
                />
              </div>
            </TableCell>
            <TableCell className="bg-green-500">
              <div className="flex justify-around">
                <Input
                  className="bg-green-500 text-white w-8 text-center"
                  placeholder="4"
                  type="text"
                />
                <span>-</span>
                <Input
                  className="bg-green-500 text-white w-8 text-center"
                  placeholder="5"
                  type="text"
                />
              </div>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="bg-gray-700 text-white">Paweł</TableCell>
            <TableCell className="bg-red-500">
              <div className="flex justify-around">
                <Input
                  className="bg-red-500 text-white w-8 text-center"
                  placeholder="4"
                  type="text"
                />
                <span>-</span>
                <Input
                  className="bg-red-500 text-white w-8 text-center"
                  placeholder="6"
                  type="text"
                />
              </div>
            </TableCell>
            <TableCell className="bg-green-500">
              <div className="flex justify-around">
                <Input
                  className="bg-green-500 text-white w-8 text-center"
                  placeholder="4"
                  type="text"
                />
                <span>-</span>
                <Input
                  className="bg-green-500 text-white w-8 text-center"
                  placeholder="6"
                  type="text"
                />
              </div>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="bg-gray-700 text-white">Łukasz</TableCell>
            <TableCell className="bg-red-500">
              <div className="flex justify-around">
                <Input
                  className="bg-red-500 text-white w-8 text-center"
                  placeholder="4"
                  type="text"
                />
                <span>-</span>
                <Input
                  className="bg-red-500 text-white w-8 text-center"
                  placeholder="7"
                  type="text"
                />
              </div>
            </TableCell>
            <TableCell className="bg-green-500">
              <div className="flex justify-around">
                <Input
                  className="bg-green-500 text-white w-8 text-center"
                  placeholder="4"
                  type="text"
                />
                <span>-</span>
                <Input
                  className="bg-green-500 text-white w-8 text-center"
                  placeholder="7"
                  type="text"
                />
              </div>
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </div>
  );
}
